### ISSUE TITLE
Tracking issue for

### ISSUE THREAD

**Issue by botsarefuture** [mountainland/ordersystem-frontend#132]
Tracking issue:
- [x] #133
- [x] #134
- [x] #135
- [x] #136
- [x] #137
- [x] #138
- [x] #139
- [x] #140
- [x] #141
- [x] #142
- [ ] #143
- [x] #144
- [x] #145
- [x] #146
- [x] #147
- [x] #149
- [x] #148
- [x] #150
- [x] #151
- [x] #152
- [x] #153
- [x] #154
- [x] #155
- [x] #156
- [x] #157
- [x] #158
- [x] #159
- [x] #160
- [x] #161
- [x] #162
- [x] #163
- [x] #164
- [ ] accounts/views.py third party import "from django.shortcuts import render" should be placed before "from .models import Code"
- [ ] accounts/views.py third party import "from django.shortcuts import redirect" should be placed before "from .models import Code"
- [ ] accounts/views.py Missing function or method docstring
- [ ] accounts/views.py Function name "SignUp" doesn't conform to snake_case naming style
- [ ] accounts/views.py Unnecessary parens after 'if' keyword
- [ ] accounts/views.py Line too long (130/100)
- [ ] Ordersystem/urls.py Unable to import 'django.urls'
- [ ] Ordersystem/urls.py Unable to import 'django.contrib'
- [ ] Ordersystem/urls.py Unable to import 'django.conf'
- [ ] Ordersystem/urls.py Unable to import 'django.conf.urls.static'
- [ ] Ordersystem/urls.py Import "django.urls" could not be resolved from source
- [ ] Ordersystem/urls.py Import "django.contrib" could not be resolved from source
- [ ] Ordersystem/urls.py Import "django.contrib.admin" could not be resolved from source
- [ ] Ordersystem/urls.py Import "django.conf" could not be resolved from source
- [ ] Ordersystem/urls.py Import "django.conf.urls.static" could not be resolved from source
- [ ] Ordersystem/urls.py Line too long (175/100)
- [ ] Product/views.py Unable to import 'django.views.generic'
- [ ] Product/views.py Unable to import 'django.shortcuts'
- [ ] Product/views.py Unable to import 'django.contrib.auth.decorators'
- [ ] Product/views.py Unable to import 'django.utils.decorators'
- [ ] Product/views.py Unable to import 'django.conf'
- [ ] Product/views.py Unable to import 'django'
- [ ] Product/views.py Bad first argument 'CreateView' given to super()
- [ ] Product/views.py Import "django.views.generic" could not be resolved from source
- [ ] Product/views.py Import "django.shortcuts" could not be resolved from source
- [ ] Product/views.py Import "django.contrib.auth.decorators" could not be resolved from source
- [ ] Product/views.py Import "django.utils.decorators" could not be resolved from source
- [ ] Product/views.py Import "django.conf" could not be resolved from source
- [ ] Product/views.py Import "django" could not be resolved from source
- [ ] Product/views.py Assigning the same variable 'PRODUCTS_URL' to itself
- [ ] Product/views.py Missing timeout argument for method 'requests.get' can cause your program to hang indefinitely
- [ ] Product/views.py Unused argument 'args'
- [ ] Product/views.py Unused argument 'kwargs'
- [ ] Product/views.py Redefining name 'PRODUCT_COUNT' from outer scope (line 15)
- [ ] Product/views.py Unused variable 'PRODUCT_COUNT'
- [ ] Product/views.py Unused argument 'kwargs'
- [ ] Product/views.py Unused argument 'object_list'
- [ ] Product/views.py Missing timeout argument for method 'requests.get' can cause your program to hang indefinitely
- [ ] Product/views.py Missing timeout argument for method 'requests.post' can cause your program to hang indefinitely
- [ ] Product/views.py Missing module docstring
- [ ] Product/views.py third party import "import django" should be placed before "from Product.products import product"
- [ ] Product/views.py third party import "import requests" should be placed before "from Product.products import product"
- [ ] Product/views.py Missing function or method docstring
- [ ] Product/views.py Missing class docstring
- [ ] Product/views.py Missing function or method docstring
- [ ] Product/views.py Missing class docstring
- [ ] Product/views.py Missing function or method docstring
- [ ] Product/views.py Missing function or method docstring
- [ ] Product/views.py Missing function or method docstring
- [ ] Ordersystem/settings.py TODO #55 Remove all related to media folder
